"""empty message

Revision ID: 0c5fa0111bcf
Revises: e35ba562d28d
Create Date: 2025-07-06 11:14:48.695450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5fa0111bcf'
down_revision: Union[str, Sequence[str], None] = 'e35ba562d28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdbfiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pdbData', sa.String(), nullable=False),
    sa.Column('protein_length', sa.Integer(), nullable=False),
    sa.Column('unique_chains', sa.String(), nullable=False),
    sa.Column('chain_count', sa.Integer(), nullable=False),
    sa.Column('chain_lengths', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdbfiles_filename'), 'pdbfiles', ['filename'], unique=True)
    op.create_index(op.f('ix_pdbfiles_id'), 'pdbfiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdbfiles_id'), table_name='pdbfiles')
    op.drop_index(op.f('ix_pdbfiles_filename'), table_name='pdbfiles')
    op.drop_table('pdbfiles')
    # ### end Alembic commands ###
