"""empty message

Revision ID: cfcd007aab64
Revises: 0c5fa0111bcf
Create Date: 2025-07-06 13:41:59.335471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcd007aab64'
down_revision: Union[str, Sequence[str], None] = '0c5fa0111bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpnn_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suppress_print', sa.Boolean(), nullable=True),
    sa.Column('ca_only', sa.Boolean(), nullable=True),
    sa.Column('path_to_model_weights', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('use_soluble_model', sa.Boolean(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('save_score', sa.Boolean(), nullable=True),
    sa.Column('save_probs', sa.Boolean(), nullable=True),
    sa.Column('score_only', sa.Boolean(), nullable=True),
    sa.Column('path_to_fasta', sa.String(), nullable=True),
    sa.Column('conditional_probs_only', sa.Boolean(), nullable=True),
    sa.Column('conditional_probs_only_backbone', sa.Boolean(), nullable=True),
    sa.Column('unconditional_probs_only', sa.Boolean(), nullable=True),
    sa.Column('backbone_noise', sa.Float(), nullable=True),
    sa.Column('num_seq_per_target', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('sampling_temp', sa.String(), nullable=True),
    sa.Column('out_folder', sa.String(), nullable=True),
    sa.Column('pdb_path', sa.String(), nullable=True),
    sa.Column('pdb_path_chains', sa.String(), nullable=True),
    sa.Column('jsonl_path', sa.String(), nullable=True),
    sa.Column('chain_id_jsonl', sa.String(), nullable=True),
    sa.Column('fixed_positions_jsonl', sa.String(), nullable=True),
    sa.Column('omit_AAs', sa.String(), nullable=True),
    sa.Column('bias_AA_jsonl', sa.String(), nullable=True),
    sa.Column('bias_by_res_jsonl', sa.String(), nullable=True),
    sa.Column('omit_AA_jsonl', sa.String(), nullable=True),
    sa.Column('pssm_jsonl', sa.String(), nullable=True),
    sa.Column('pssm_multi', sa.Float(), nullable=True),
    sa.Column('pssm_threshold', sa.Float(), nullable=True),
    sa.Column('pssm_log_odds_flag', sa.Boolean(), nullable=True),
    sa.Column('pssm_bias_flag', sa.Boolean(), nullable=True),
    sa.Column('tied_positions_jsonl', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpnn_jobs')
    # ### end Alembic commands ###
